### PR TITLE
5e aura

### LINKED ISSUE #16: More types of auras
* AURA type that only works once. Anyone leaving the aura will not get it back when they re-enter.
* AURA type that keeps working when a creature leaves the aura.

### PR DESCRIPTION
**Pull request by rhagelstrom**
Added 5e aura type and cleaned up some of the aura faction stuff to not be so brittle. Motivation behind the 5e aura type to name a few is:
https://www.dndbeyond.com/spells/spirit-guardians
https://www.dndbeyond.com/spells/cloud-of-daggers
https://www.dndbeyond.com/spells/cloudkill

Updated the readme if you want to read up on it a bit more

Tested but probably would be good to put on test for a while.

fixes #16

### CODE REVIEW

**Comment by bmos** [comment]
Very coo!
I think the 5e nomenclature might be too specific though as this behavior is definitely present in 3.5e (and likely others).

**Comment by rhagelstrom** [comment]
I'm not tied to 5e aura type. I just couldn't think of anything better for a name.

Known conflict with b9 spell tokens. He is apparently notifying aura with a OOB_MSGTYPE_AURATOKENMOVE that tokens are moving that aren't actually moving. Probably need something for him to test against before notified

**Comment by rhagelstrom** [comment]
BCE Test Case;
-5e
Spirit Guardians (C); AURA: 15 !ally,5e; Spirit Guardians; IF: FACTION(notself); SAVEA: 15 WIS (M)(H); SAVES: 15 WIS (M)(H); SAVEDMG: 3d8 radiant

- 3.5
Spirit Guardians AURA: 15 !ally,5e; Spirit Guardians; IF: FACTION(notself); SAVEA: 15 WILL (M)(H); SAVES: 15 WILL (M)(H); SAVEDMG: 3d8 radiant

**Comment by bmos** [comment]
> I'm not tied to 5e aura type. I just couldn't think of anything better for a name.

maybe: ```,single``` or ```,once```.

**Comment by bmos** [comment]
> Known conflict with b9 spell tokens. He is apparently notifying aura with a OOB_MSGTYPE_AURATOKENMOVE that tokens are moving that aren't actually moving. Probably need something for him to test against before notified

Just a conflict with your PR active, you mean?
He could probably call Token.onMove.

**Comment by rhagelstrom** [comment]
I'll update the PR and go with single. Yes conflict with my PR. He is aware of it and it is 100% spell tokens ext. Nothing I can do about it if data getting sent to me isn't correct.

**Comment by rhagelstrom** [comment]
@bmos Should be good to go unless you have other issues with the PR

**Pull request merged**
