### PR TITLE
More Updates!

### PR DESCRIPTION
**Pull request by rhagelstrom**
Sorry I kind of went a bit wild but I wanted to clean up some of this Kent legacy stuff and move things more in line with FG
You'll want to look/try this before you merge it incase you hate something I changed in particular
f577428 - which changes up a bit on how the FACTION conditional works
0ab79be - which gets ride of FROMAURA completely because it is no longer needed

I think I got rid of all the expensive loops so it should run pretty snappy.

I tried it quick in PF1E and works for me. There isn't really any reason it shouldn't work as its all core with expiation of the conditional.

If you are going to cut a release I'd suggest throw it on test first since so much code has changed.

### CODE REVIEW

**Comment by bmos** [comment]
This looks incredible.
Should be able to test it out early this week.

**Comment by rhagelstrom** [comment]
Thank you. 
I thought about doing the fromaura duration roll request but maybe another day. One of those things might be quick until it’s not

**Comment by bmos** [comment]
OK here's what I have found so far:
* If you open a map and move tokens around without having opened the combat tracker first, auras don't work.
* It's SO much faster. I'm sure SilentRuin will be annoyed with the changes, but his complicated test scenarios should be much quicker.

**Comment by rhagelstrom** [comment]
I also had a report of single not behaving like expected but haven't confirmed. I bet map before CT is what happened last time you tried it. That should be an easy fix *knock on wood*

SR wants things to work for him and doesn't care about anyone else. It'll be interesting if he complains about having to change his faction checks or token factions because he is doing one thing or another in whatever he does.

**Pull request merged**
