### PR TITLE
Fixes #37 

### LINKED ISSUE #37: Auras don't update when tokens are added
If you create a CT entry and add an aura effect to it and then add the token to the map, it doesn't take effect until the token is moved.
https://www.fantasygrounds.com/forums/showthread.php?57417-5E-Aura-Effects&p=717488&viewfull=1#post717488

### PR DESCRIPTION
**Pull request by rhagelstrom**
Adding token to map with aura didn't bootstrap the aura. Deleting token from map didn't remove applied auras

### CODE REVIEW

**Comment by rhagelstrom** [comment]
The second commit should help people want to override stuff.

**Comment by bmos** [comment]
Awesome! Thank you! I will check this out and release this weekend.

**Comment by bmos** [comment]
Seems to be working great!
Any thoughts on handling adding/removing tokens within the range of existing auras?
If someone summons something, for example, it should have the effect added when it's added to the map.
It looks like probably we would have to recalculate auras for all tokens when adding/removing a token rather than just calculating auras for that one token. Does that seems reasonable?

**Comment by rhagelstrom** [comment]
yes that is probably reasonable case I didn't consider. Simple enough change. I'm out of town the rest of the weekend so I probably wouldn't get to that until sometime next week unless you get to it first.

I have some other ideas that I'm working on. One thing that I think needs to change a bit is the range calc for boundary conditions on what applies and what doesn't. The cube right now is for sure wrong and the sphere might be wrong depending on ruleset and/or some cases and I'm not sure if something is large or bigger is always right.

Deep diving into what AoE applies to is really poorly defined or more of guidelines. 2E from what I can gather from the DMG is touches. 5E is all over the place and is more of guidelines, one place more than half in, another touches. PF2 I need to do more reading but I think it's use those templates which comes out to math so they are probably the best on it. 3.5 I haven't really dived into and maybe you know. I suspect it is also probably not entirely clear. 

Also heard that SW is actively working on some sort of area of effect implementation which is great but I guess we will wait and see how fleshed out or not that is.

**Comment by bmos** [comment]
3.5E is actually pretty clear, but I don't know how often this is actually treated this way. My groups sure don't.
https://www.d20pfsrd.com/gamemastering/combat/space-reach-threatened-area-templates/

**Pull request merged**
