### PR TITLE
Movefilter

### PR DESCRIPTION
**Pull request by rhagelstrom**
Fixes the B9 Spell Tokens issue with single aura type
Added ability to define a Cube aura
Added some aura tracking so that the overabundance of searching nodes for effects that end up fruitless is greatly reduced. Should see performance gains especially for situations where there are a lot of CT actors and/or lots of effects in the CT. I don't have any numbers on the gains however.

There was also a second aura type in issue #16 about not falling off when out of range. I don't know the use case for that so I don't really understand the ask.

### CODE REVIEW

**Comment by bmos** [comment]
the other aura type mentioned in #16 is auras that 'stick' when acquired.
so if you enter the aura and then leave, you still have it.

**Comment by rhagelstrom** [comment]
Is it suppose to go away if the source aura goes away? Do you get it again if you reenter? I assume no to the latter

**Comment by bmos** [comment]
No to both.
This would be for some effects from things like poisonous gasses and the like.
I have realized after merging this that it's not working in 3.5E.

**Comment by rhagelstrom** [comment]
Balls! What isn't working? I'll see if I can find some time this weekend maybe.

**Comment by rhagelstrom** [comment]
If you want to roll the commits back I can just do another PR once whatever the problem is resolved. Whatever works for you

**Comment by bmos** [comment]
No need to roll back. Auras are not recalculating when tokens are moved, only when the map is loaded. Probably an easy fix. I'll have time this weekend also.

**Pull request merged**
