### PR TITLE
Client side distance calculation

### PR DESCRIPTION
**Pull request by SoxMax**
Because of the change to `EffectManager.addEffect` the `bShowMsg` flag is now suppressing error messaging when applying effects. I've switch back from the OOB to directly calculating aura effects on the client and it seems to pretty reliably add/remove effects without any messaging when Silent Auras is on.

I tested on PFRPG and 4E.

### CODE REVIEW

**Comment by SoxMax** [comment]
@bmos do you think we should do a 1.0 release after this?

**Comment by bmos** [comment]
I think so!
Great work on this!

**Comment by SoxMax** [comment]
I've got a session tonight and if everything goes well I'll squash and merge this.

**Comment by SoxMax** [comment]
OK something really odd was happening with Locked Movement & the auras. I'm going to see if its possible to detect if locked movement is on and if so use the OOB otherwise let the clients calculate.

**Comment by SoxMax** [comment]
I added a check for token movement locking to use OOB. That said I'm not super thrilled about having the if check on every onMove event. I'm going to see about re-registering the onMove event depending on the state of the Token Movement Locking.

**Comment by bmos** [comment]
Here is Moon Wizard's advice:
https://www.fantasygrounds.com/forums/showthread.php?68078-Issue-with-getTokensWithinDistance/page2

**Comment by SoxMax** [comment]
Oh man a bug fix and a code simplification? This is awesome. I'm much more comfortable with this hack then until 4.1 comes out.

**Comment by SoxMax** [comment]
Apparently `Token.onMove` exists currently as well its just not documented. I updated to use that as Moon Wizard recommended.
Even with that though we still need the OOB & raw calculation based on movement locking mode until 4.1 comes out.

**Comment by SoxMax** [comment]
I'll merge this afternoon

**Pull request merged**
